# layer_4_analytics/schemas/knowledge_gap.py

from datetime import datetime, timezone
from typing import Literal
from pydantic import BaseModel, Field, ConfigDict, model_validator


GapSeverityTier = Literal["low", "medium", "high"]


GapActionType = Literal[
    "CREATE_FAQ_ARTICLE",
    "UPDATE_EXISTING_ARTICLE",
    "ADD_PRODUCT_DOCUMENTATION",
    "IMPROVE_WORKFLOW",
    "ESCALATE_TO_PRODUCT_TEAM"
]


class KnowledgeGap(BaseModel):
    """
    Feedback Intelligence contract representing a semantically clustered failure vector,
    identifying recurring customer friction topics, specific text evidence, and
    actionable documentation remediations.
    """

    model_config = ConfigDict(
        from_attributes=True,
        populate_by_name=True,
        validate_assignment=True,
        json_schema_extra={
            "example": {
                "cluster_id": "kg_sub_cancellation",
                "topic": "Subscription Cancellation Process",
                "occurrences": 47,
                "severity": "HIGH",
                "satisfaction_rate": 34.20,
                "sample_questions": [
                    "How do I cancel my subscription?",
                    "How can I stop auto-renew billing?",
                    "Where do I end my membership?"
                ],
                "suggested_article_title": "How to Cancel or Pause Your Subscription",
                "suggested_action": "CREATE_FAQ_ARTICLE",
                "detected_at": "2026-06-11T10:39:00Z"
            }
        }
    )


    cluster_id: str = Field(
        ...,
        min_length=3,
        description="Stable alphanumeric semantic cluster token generated by the KnowledgeGapService (e.g., 'kg_sub_cancellation')"
    )
    topic: str = Field(
        ...,
        min_length=1,
        description="Human-readable theme label derived via semantic text extraction"
    )

   
    occurrences: int = Field(
        ...,
        ge=1,
        description="The absolute frequency count of failed interactions clustered into this specific topic vector"
    )
    severity: GapSeverityTier = Field(
        ...,
        description="The operational prioritization severity calculated directly from volume metrics and satisfaction rate deficits"
    )
    satisfaction_rate: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="The rolling customer satisfaction score (CSAT) calculated exclusively across this failure cluster"
    )


    sample_questions: list[str] = Field(
        ...,
        min_length=1,
        max_length=10,
        description="A list containing up to 10 typical customer question examples extracted from the raw interaction text"
    )

 
    suggested_article_title: str = Field(
        ...,
        min_length=1,
        description="The generated, optimized heading recommendation for new or updated documentation text"
    )
    suggested_action: GapActionType = Field(
        ...,
        description="Standardized action classification mapping the specific operational step needed to resolve the gap"
    )

    
    detected_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="The exact timezone-aware UTC timestamp capturing when this intelligence assessment was compiled"
    )

    @model_validator(mode="after")
    def validate_intelligence_and_temporal_integrity(self) -> "KnowledgeGap":
        """
        Validates internal consistency across severity, text sample boundaries,
        and strict timezone-aware UTC constraints.
        """
       
        if self.occurrences >= 40 or self.satisfaction_rate <= 40.0:
            if self.severity != "high":
                raise ValueError(
                    f"Prioritization mismatch for cluster '{self.cluster_id}': With {self.occurrences} "
                    f"occurrences and a satisfaction rate of {self.satisfaction_rate}%, severity must be explicitly set to 'HIGH'."
                )
        elif self.occurrences < 15 and self.satisfaction_rate >= 75.0:
            if self.severity != "low":
                raise ValueError(
                    f"Prioritization mismatch for cluster '{self.cluster_id}': Low volume and high "
                    f"satisfaction ({self.satisfaction_rate}%) must be classified as 'LOW' severity."
                )

       
        if self.detected_at.tzinfo is None:
            raise ValueError(
                f"Timezone constraint violation for cluster '{self.cluster_id}': "
                f"detected_at must be explicitly instantiated as a timezone-aware datetime object."
            )
        if self.detected_at.utcoffset() != timezone.utc.utcoffset(self.detected_at):
            raise ValueError(
                f"Data isolation violation for cluster '{self.cluster_id}': "
                f"detected_at uses a non-UTC offset ({self.detected_at.tzinfo}). All analytics data must be strictly UTC normalized."
            )

        return self