import logging
import time
from typing import Optional

from layer_3.schemas.translation_result import TranslationResult
from layer_3.protection.format_and_entity_protector import FormatAndEntityProtector
from layer_3.translation.helsinki_translator import HelsinkiTranslator
from layer_3.translation.translation_validator import TranslationValidator
from layer_3.translation.translation_cache import TranslationCache

logger = logging.getLogger(__name__)


TRANSLATION_PROVIDER = "helsinki"
SUPPORTED_OUTBOUND_LANGUAGES = {"hi", "es", "fr", "de", "ar"}

class OutboundTranslationPipeline:
    """
    The Orchestrator for Layer 3 (Outbound).
    Converts English responses generated by Specialist Agents back into 
    the customer's native language, safely protecting all CRM variables.
    """

    def __init__(self):
        self.protector = FormatAndEntityProtector()
        self.translator = HelsinkiTranslator()
        self.validator = TranslationValidator()
        self.cache = TranslationCache()

    def process_outbound(self, english_response: str, target_language: str, source_agent: Optional[str] = None) -> TranslationResult:
        """
        Executes the 8-step outbound translation workflow.
        Returns a TranslationResult containing customer-facing text and timing telemetry.
        """
        start_time = time.perf_counter()

       
        if not english_response or not english_response.strip():
            return self._build_result(english_response, target_language, True, start_time)

    
        if target_language == "en":
            logger.info("Outbound Pipeline | English Fast Path Triggered")
            return self._build_result(english_response, "en", True, start_time)

   
        if target_language not in SUPPORTED_OUTBOUND_LANGUAGES:
            logger.warning(f"Outbound Translation Failed | TargetLanguage={target_language} | Reason=UnsupportedLanguage")
            return self._build_result(english_response, target_language, False, start_time)

        logger.info(f"Outbound Pipeline | Translating response from en to {target_language} | Agent={source_agent or 'unknown'}")

      
        protected_content = self.protector.protect(english_response)

  
        cached_result = self.cache.get(
            text=protected_content.protected_text,
            source_language="en",
            target_language=target_language
        )

        if cached_result:
     
            logger.info(f"Outbound Pipeline | CacheHit | TargetLanguage={target_language}")
            final_translated_text = cached_result.translated_text
            translation_success = cached_result.translation_success
        else:
     
            logger.info(f"Outbound Pipeline | CacheMiss | TargetLanguage={target_language}")
            
            
            translation_result = self.translator.translate(
                text=protected_content.protected_text,
                source_language="en",
                target_language=target_language
            )

            
            is_valid = self.validator.validate(
                original_text=protected_content.protected_text,
                translated_text=translation_result.translated_text
            )

           
            if not is_valid or not translation_result.translation_success:
                logger.warning(f"Outbound Translation Failed | TargetLanguage={target_language} | Reason=ValidationOrTranslationError")
                return self._build_result(english_response, target_language, False, start_time)

            final_translated_text = translation_result.translated_text
            translation_success = translation_result.translation_success 
            
           
            self.cache.set(
                text=protected_content.protected_text,
                source_language="en",
                target_language=target_language,
                translation_result=translation_result
            )

    
        customer_facing_text = self.protector.restore(
            final_translated_text,
            protected_content
        )

        
        return self._build_result(customer_facing_text, target_language, translation_success, start_time)

    def _build_result(self, translated_text: str, target_language: str, success: bool, start_time: float) -> TranslationResult:
        """Standardizes metric collection and duration processing for outbound traffic logging."""
        duration_ms = round((time.perf_counter() - start_time) * 1000)
        logger.info(f"Outbound Pipeline Complete | Target={target_language} | DurationMs={duration_ms} | Success={success}")
        
        return TranslationResult(
            translated_text=translated_text,
            source_language="en",
            target_language=target_language,
            translation_service=TRANSLATION_PROVIDER,
            translation_success=success
        )