from datetime import datetime, UTC

from pydantic import (
    BaseModel,
    Field,
    ConfigDict
)

class OutreachMessage(BaseModel):
    """
    Output produced by message_generation_node.

    Represents the final customer-facing outreach message 
    generated by the LLM layer.

    Verified against DB constraints:
    - generated_at -> timestamp with time zone (Enforced via UTC datetime)
    """

    model_config = ConfigDict(
        frozen=True,
        json_schema_extra={
            "example": {
                "subject": "We wanted to check in",
                "body": (
                    "Hi Rahul,\n\n"
                    "We noticed you haven't been active recently "
                    "and wanted to make sure everything is going well."
                ),
                "channel": "email",
                "generated_by": "llama3-70b-8192",
                "generated_at": "2026-05-31T20:30:00Z"
            }
        }
    )

    subject: str = Field(..., description="Subject line of the outreach message.")
    body: str = Field(..., description="Generated outreach message content.")
    channel: str = Field(default="email", description="Delivery channel.")
    generated_by: str = Field(..., description="Model or system responsible for generation.")
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="UTC timestamp when the message was generated. Matches timestamp with time zone columns."
    )