"""sync metadata

Revision ID: edb4aaf35ef3
Revises: b1b3ec865383
Create Date: 2026-06-27 19:49:31.270566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edb4aaf35ef3'
down_revision: Union[str, Sequence[str], None] = 'b1b3ec865383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_churn_alerts_customer_id'), 'churn_alerts', ['customer_id'], unique=False)
    op.alter_column('crm_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('customer_support_profiles', 'total_tickets',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_faq_tickets',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_refund_tickets',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_account_tickets',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_escalations',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_denials',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_failures',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_clarifications',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_duplicate_suppressions',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'repeat_negative_count',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'repeat_escalation_count',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'duplicate_request_count',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'negative_ticket_count',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ticket_transcripts_customer_id'), 'ticket_transcripts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ticket_transcripts_intent'), 'ticket_transcripts', ['intent'], unique=False)
    op.alter_column('translation_records', 'customer_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translation_records', 'customer_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_ticket_transcripts_intent'), table_name='ticket_transcripts')
    op.drop_index(op.f('ix_ticket_transcripts_customer_id'), table_name='ticket_transcripts')
    op.alter_column('customer_support_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customer_support_profiles', 'negative_ticket_count',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'duplicate_request_count',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'repeat_escalation_count',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'repeat_negative_count',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_duplicate_suppressions',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_clarifications',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_failures',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_denials',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_escalations',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_account_tickets',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_refund_tickets',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_faq_tickets',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('customer_support_profiles', 'total_tickets',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('crm_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_churn_alerts_customer_id'), table_name='churn_alerts')
    # ### end Alembic commands ###
