from datetime import datetime
from pydantic import BaseModel, Field
from layer_4_analytics.schemas.dashboard_snapshot import DashboardSnapshot

class MasterDashboardResponse(BaseModel):
    """The complete monolith payload for the Executive Dashboard UI."""
    generated_at: datetime = Field(
        ..., 
        description="The exact UTC timestamp when this dashboard was calculated."
    )
    summary_report: str = Field(
        ..., 
        description="The formatted text report generated by the ExecutiveSummaryService."
    )
    snapshot: DashboardSnapshot = Field(
        ..., 
        description="The massive structured data object containing Agent, Intent, Churn, and ROI metrics."
    )